---
title: ActiveSyncException
second_title: Aspose.Email for .NET API 参考
description: 初始化ActiveSyncExceptionaspose.email/activesyncexception具有指定错误消息的类
type: docs
weight: 10
url: /zh/net/aspose.email/activesyncexception/activesyncexception/
---
## ActiveSyncException(string) {#constructor_2}

初始化[`ActiveSyncException`](../../activesyncexception)具有指定错误消息的类。

```csharp
public ActiveSyncException(string message)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 描述错误的消息。 |

### 也可以看看

* class [ActiveSyncException](../../activesyncexception)
* 命名空间 [Aspose.Email](../../activesyncexception)
* 部件 [Aspose.Email](../../../)

---

## ActiveSyncException() {#constructor}

初始化[`ActiveSyncException`](../../activesyncexception)类.

```csharp
public ActiveSyncException()
```

### 也可以看看

* class [ActiveSyncException](../../activesyncexception)
* 命名空间 [Aspose.Email](../../activesyncexception)
* 部件 [Aspose.Email](../../../)

---

## ActiveSyncException(string, Exception) {#constructor_3}

初始化[`ActiveSyncException`](../../activesyncexception)类 带有指定的错误消息和对导致此异常的内部异常的引用。

```csharp
public ActiveSyncException(string message, Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 解释异常原因的错误消息。 |
| innerException | Exception | 作为当前异常原因的异常，如果没有指定内部异常，则为空引用（在 Visual Basic 中为 Nothing）。 |

### 也可以看看

* class [ActiveSyncException](../../activesyncexception)
* 命名空间 [Aspose.Email](../../activesyncexception)
* 部件 [Aspose.Email](../../../)

---

## ActiveSyncException(Exception) {#constructor_1}

初始化[`ActiveSyncException`](../../activesyncexception)类 引用了导致此异常的内部异常。

```csharp
public ActiveSyncException(Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| innerException | Exception | 作为当前异常原因的异常，如果没有指定内部异常，则为空引用（在 Visual Basic 中为 Nothing）。 |

### 也可以看看

* class [ActiveSyncException](../../activesyncexception)
* 命名空间 [Aspose.Email](../../activesyncexception)
* 部件 [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
