---
title: FileAccessViolationException
second_title: Aspose.Email for .NET API 参考
description: 使用默认错误消息初始化类的新实例
type: docs
weight: 10
url: /zh/net/aspose.email.mapi/fileaccessviolationexception/fileaccessviolationexception/
---
## FileAccessViolationException() {#constructor}

使用默认错误消息初始化类的新实例。

```csharp
public FileAccessViolationException()
```

### 也可以看看

* class [FileAccessViolationException](../../fileaccessviolationexception)
* 命名空间 [Aspose.Email.Mapi](../../fileaccessviolationexception)
* 部件 [Aspose.Email](../../../)

---

## FileAccessViolationException(string) {#constructor_1}

使用指定的错误消息初始化类的新实例。

```csharp
public FileAccessViolationException(string message)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 错误消息。 |

### 也可以看看

* class [FileAccessViolationException](../../fileaccessviolationexception)
* 命名空间 [Aspose.Email.Mapi](../../fileaccessviolationexception)
* 部件 [Aspose.Email](../../../)

---

## FileAccessViolationException(string, Exception) {#constructor_2}

使用 指定错误消息和对内部 异常的引用初始化 Exception 类的新实例是此异常的原因。

```csharp
public FileAccessViolationException(string message, Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 解释异常原因的错误消息。 |
| innerException | Exception | 导致当前异常的异常。 如果 innerException 参数不是 NULL 引用 （在 Visual Basic 中为无），则在处理内部的 catch 块中引发当前异常 例外。 |

### 也可以看看

* class [FileAccessViolationException](../../fileaccessviolationexception)
* 命名空间 [Aspose.Email.Mapi](../../fileaccessviolationexception)
* 部件 [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
