---
title: FileAccessViolationException.FileAccessViolationException
second_title: Aspose.Email for .NET API Reference
description: FileAccessViolationException constructor. Initializes a new instance of the class with default error message
type: docs
weight: 10
url: /net/aspose.email.mapi/fileaccessviolationexception/fileaccessviolationexception/
---
## FileAccessViolationException() {#constructor}

Initializes a new instance of the class with default error message.

```csharp
public FileAccessViolationException()
```

### See Also

* class [FileAccessViolationException](../)
* namespace [Aspose.Email.Mapi](../../fileaccessviolationexception/)
* assembly [Aspose.Email](../../../)

---

## FileAccessViolationException(string) {#constructor_1}

Initializes a new instance of the class with a specified error message.

```csharp
public FileAccessViolationException(string message)
```

| Parameter | Type | Description |
| --- | --- | --- |
| message | String | Error message. |

### See Also

* class [FileAccessViolationException](../)
* namespace [Aspose.Email.Mapi](../../fileaccessviolationexception/)
* assembly [Aspose.Email](../../../)

---

## FileAccessViolationException(string, Exception) {#constructor_2}

Initializes a new instance of the Exception class with a specified error message and a reference to the inner exception that is the cause of this exception.

```csharp
public FileAccessViolationException(string message, Exception innerException)
```

| Parameter | Type | Description |
| --- | --- | --- |
| message | String | The error message that explains the reason for the exception. |
| innerException | Exception | The exception that is the cause of the current exception. If the innerException parameter is not a NULL reference (Nothing in Visual Basic), the current exception is raised in a catch block that handles the inner exception. |

### See Also

* class [FileAccessViolationException](../)
* namespace [Aspose.Email.Mapi](../../fileaccessviolationexception/)
* assembly [Aspose.Email](../../../)


